# Generated by Django 5.2.7 on 2025-11-03 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.SlugField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('edad', models.PositiveSmallIntegerField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=12)),
                ('nombre_rol', models.CharField(choices=[('usuario', 'Usuario'), ('administracion', 'Administración'), ('mantenimiento', 'Mantenimiento')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Usa negativos para subterráneos (−1, −2), 0 para zócalo si aplica, 1..N para niveles.', validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(200)])),
                ('etiqueta', models.CharField(blank=True, help_text="Opcional: etiqueta visible (p. ej., 'Subterráneo 1', '2° Piso')", max_length=40)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pisos', to='app.edificio')),
            ],
            options={
                'ordering': ['edificio', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('prioridad', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reportes/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('pausado', 'Pausado'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asignados', to='app.registrousuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_creados', to='app.registrousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: H-201, H-203B', max_length=50)),
                ('nombre', models.CharField(blank=True, help_text="Nombre legible: 'Laboratorio Redes'", max_length=120)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='app.edificio')),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='app.piso')),
            ],
            options={
                'ordering': ['edificio', 'piso__numero', 'codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='piso',
            constraint=models.UniqueConstraint(fields=('edificio', 'numero'), name='piso_unico_por_edificio'),
        ),
        migrations.AddConstraint(
            model_name='sala',
            constraint=models.UniqueConstraint(fields=('edificio', 'codigo'), name='codigo_sala_unico_por_edificio'),
        ),
    ]
