# Generated by Django 5.2.7 on 2025-11-07 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piso',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='piso',
            name='numero',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='sala',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
