# Generated by Django 5.2.7 on 2025-10-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reportes/'),
        ),
    ]
