# Generated by Django 5.2.7 on 2025-11-12 18:22

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_piso_etiqueta_alter_piso_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', app.models.UsuarioManager()),
            ],
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
