# Generated by Django 5.2.7 on 2025-10-28 02:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoria_genero_prioridad_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.SlugField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Usa negativos para subterráneos (−1, −2), 0 para zócalo si aplica, 1..N para niveles.', validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(200)])),
                ('etiqueta', models.CharField(blank=True, help_text="Opcional: etiqueta visible (p. ej., 'Subterráneo 1', '2° Piso')", max_length=40)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pisos', to='app.edificio')),
            ],
            options={
                'ordering': ['edificio', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: H-201, H-203B', max_length=50)),
                ('nombre', models.CharField(blank=True, help_text="Nombre legible: 'Laboratorio Redes'", max_length=120)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='app.edificio')),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='app.piso')),
            ],
            options={
                'ordering': ['edificio', 'piso__numero', 'codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='piso',
            constraint=models.UniqueConstraint(fields=('edificio', 'numero'), name='piso_unico_por_edificio'),
        ),
        migrations.AddConstraint(
            model_name='sala',
            constraint=models.UniqueConstraint(fields=('edificio', 'codigo'), name='codigo_sala_unico_por_edificio'),
        ),
    ]
