# Generated by Django 5.2.7 on 2025-11-12 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuario_managers_reporte_fecha_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='fecha_ultima_reasignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistorialAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_de', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_a', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_asignado_hacia', to=settings.AUTH_USER_MODEL)),
                ('asignado_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_asignado_desde', to=settings.AUTH_USER_MODEL)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cambios_asignacion', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asignaciones', to='app.reporte')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['reporte', 'creado_en'], name='app_histori_reporte_44b012_idx'), models.Index(fields=['asignado_a'], name='app_histori_asignad_752ea4_idx')],
            },
        ),
    ]
