# Generated by Django 5.2.7 on 2025-11-13 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_reporte_fecha_ultima_reasignacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='reporte',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='app.sala'),
        ),
    ]
